config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'admin', to: 'admin#index', as: :admin
  get 'examples', to: 'home#index', as: :examples

  resources :categorias, only: [:index, :show] do
    resources :subcategorias, only: [:index, :show]
  end

  resources :subcategorias, only: [:index, :show] do
    resources :articulos, only: [:index, :show]
  end

  namespace :admin do
    resources :categorias do
      collection do
        match 'search' => 'categorias#search', via: [:get, :post], as: :search
      end
    end
    resources :subcategorias do
      collection do
        match 'search' => 'subcategorias#search', via: [:get, :post], as: :search
      end
    end
    resources :articulos do
      collection do
        match 'search' => 'articulos#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
      end
    end
  end

  root 'categorias#index'
end

app/models/articulo.rb
# == Schema Information
#
# Table name: articulos
#
#  id              :integer          not null, primary key
#  titulo          :string(255)
#  posicion        :integer
#  contenido       :text
#  slug            :string(255)
#  subcategoria_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Articulo < ActiveRecord::Base
  belongs_to :subcategoria
  extend FriendlyId
  friendly_id :titulo, use: :slugged
  validates :titulo, presence: true
  scope :primeros, ->{ limit(5) }
  default_scope ->{ order(:posicion) }

  def self.los_ultimos
    unscoped.order(:created_at).limit(10).reverse
  end

  def to_s
    titulo
  end
end

app/controllers/admin/articulos_controller.rb
class Admin::ArticulosController < Admin::BaseController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  def index
    @q = Articulo.includes(:subcategoria).search(params[:q])
    @articulos = @q.result(distinct: true).paginate(page: params[:page])
  end

  def show
    respond_with(@articulo)
  end

  def new
    @articulo = Articulo.new
    respond_with([:admin, @articulo])
  end

  def edit
  end

  def create
    @articulo = Articulo.new(articulo_params)
    if @articulo.save
      respond_with([:admin, @articulo])
    else
      render :new
    end
  end

  def update
    if @articulo.update(articulo_params)
      respond_with([:admin, @articulo])
    else
      render :edit
    end
  end

  def destroy
    @articulo.destroy
    respond_with([:admin, @articulo])
  end

  def search
    index
    render :index
  end

  private
  def set_articulo
    @articulo = Articulo.friendly.find(params[:id])
  end

  def articulo_params
    params.require(:articulo).permit(:titulo, :contenido, :subcategoria_id , :slug)
  end
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  respond_to :html, :json
  def index
    @articulos = Articulo.all
    respond_with(@articulos)
  end

  def show
    @articulo = Articulo.friendly.find(params[:id])
    respond_with(@articulo)
  end
end

app/views/admin/articulos/_form.html.erb
<div class='row'>
  <%= form_for [:admin, @articulo] do |f| %>
    <% if @articulo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@articulo.errors.count, "error") %> no permitieron guardar los cambios:</h2>

        <ul>
        <% @articulo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class='col-12'>
      <div class='grouped-inputs'>
        <%= f.label :titulo %>
        <%= f.text_field :titulo, placeholder: 'Título del Artículo' %>
      </div>
    </div>

    <div class='col-5'>
      <div class="grouped-inputs-select">
        <%= f.label :subcategoria %>
        <%= f.grouped_collection_select :subcategoria_id, Categoria.includes(:subcategorias).all, :subcategorias, :titulo, :id, :titulo, prompt: true %>
      </div>
    </div>
    <div class='col-5'>
      <div class='grouped-inputs'>
        <%= f.label 'Posición' %>
        <%= f.number_field :posicion, placeholder: 'Posición en número' %>
      </div>
    </div>

    <div class='col-12'>
      <div class="grouped-inputs-textarea">
        <%= f.text_area :contenido, placeholder: 'Contenido del Artículo', class: 'wysiwyg' %>
      </div>
    </div>

    <div class='col-12'>
      <br>
      <div class='float actions'>
        <%= f.submit 'Guardar', class:'btn-default push-right'  %>
        <%= link_to 'Cancelar', admin_articulos_path, class:'btn-cancel push-right' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/articulos/edit.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Artículos', admin_categorias_path %>
    <%= link_to 'Editar Artículo', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-file fa-lg"></i>
      </span>
      <h3>Editar Artículo</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/articulos/index.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Artículos', admin_articulos_path %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-9'>
      <span class='icon'>
        <i class="fa fa-file fa-lg"></i>
      </span>
      <h3>Todos los Artículos</h3>
    </div>
    <div class='col-3 float'>
      <%= link_to '<i class="fa fa-plus"></i> Agregar Artículo'.html_safe, new_admin_articulo_path , class: 'btn-default push-right mt'%>
    </div>
  </div>
  <div class='row'>
    <div class='col-12'>
      <div class='float'>
        <%= search_form_for @q, url: search_admin_articulos_path, html: {method: :post} do |f| %>
        <div class='search push-right'>
          <%= f.search_field :titulo_cont, placeholder: 'Buscar por titulo' %>
          <%= f.button 'buscar' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <%= content_tag :th, sort_link(@q, :titulo) %>
            <%= content_tag :th, sort_link(@q, :subcategoria, 'Subcategoría') %>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @articulos.each do |articulo| %>
            <tr>
              <td><%= articulo.titulo %></td>
              <td><span class='label-green'><%= articulo.subcategoria.titulo if articulo.subcategoria %></span></td>
              <td class= 'acciones'>
                <%= link_to '<i class="fa fa-plus-square fa-lg"></i>'.html_safe, admin_articulo_path(articulo), class: 'show' %>
                <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_admin_articulo_path(articulo), class: 'show' %>
                <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, admin_articulo_path(articulo), method: :delete, data: { confirm: 'Are you sure?' } , class: 'delete'%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @articulos %>
    </div>
  </div>
</div>

app/views/admin/articulos/new.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Artículos', admin_articulos_path %>
    <%= link_to 'Nuevo Artículo', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-file fa-lg"></i>
      </span>
      <h3>Nuevo Artículo</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/articulos/show.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Artículos', admin_articulos_path %>
    <%= link_to @articulo.titulo , '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-file fa-lg"></i>
      </span>
      <h3><%= @articulo.titulo %></h3>
    </div>
    <div class='col-12 info'>
      <div class='row'>
        <div class='col-12'>
          <ul>
            <li>
              La subcategoría de este artículo es <b class='green-text'><%= @articulo.subcategoria %></b>.
            </li>
          </ul>
          <hr>
          <h4>Contenido</h4>
          <p>
            <%= raw @articulo.contenido %>
          </p>
        </div>
        <div class='col-12'>
          <div class='float'>
            <%= link_to 'Editar', edit_admin_articulo_path(@articulo), class:'btn-default push-right'  %>
            <%= link_to 'regresar', admin_articulos_path, class:'btn-gray push-right'  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>