config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'admin', to: 'admin#index', as: :admin
  get 'examples', to: 'home#index', as: :examples

  resources :categorias, only: [:index, :show] do
    resources :subcategorias, only: [:index, :show]
  end

  resources :subcategorias, only: [:index, :show] do
    resources :articulos, only: [:index, :show]
  end

  namespace :admin do
    resources :categorias do
      collection do
        match 'search' => 'categorias#search', via: [:get, :post], as: :search
      end
    end
    resources :subcategorias do
      collection do
        match 'search' => 'subcategorias#search', via: [:get, :post], as: :search
      end
    end
    resources :articulos do
      collection do
        match 'search' => 'articulos#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
      end
    end
  end

  root 'categorias#index'
end

app/views/admin/_siderbarAdmin.html.erb
<div class='top-header'>
  <h2>Administrador</h2>
</div>
<ul>
  <li>
    <%= link_to '<i class="fa fa-line-chart"></i> Dashboard'.html_safe, admin_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-star"></i> Categorías'.html_safe, admin_categorias_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-th-large"></i> Subcategorías'.html_safe, admin_subcategorias_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-file"></i> Artículos'.html_safe, admin_articulos_path %>
  </li>
  <li>
    <%= link_to '<i class="fa fa-user"></i> Usuarios'.html_safe, admin_users_path %>
  </li>
</ul>
<footer>
  footer
</footer>

app/views/admin/index.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
  </div>
<% end %>

<div class='container'>
  <div class='row'>
    <div class='col-6 back-dashboard'>
      <h3 class='dash-title'><i class="fa fa-bookmark-o"></i> Total de Datos</h3>
      <div class='row'>
        <div class='col-4'>
          <%= link_to(admin_categorias_path) do %>
          <div class='circle100 text-center'><%= @categorias.count %></div>
          <h5 class='text-center'>Categorías</h5>
          <%end%>
        </div>
        <div class='col-4'>
          <div class='circle100 text-center subcategoria'><%= @subcategorias.count %></div>
          <h5 class='text-center'>Subcategorías</h5>
        </div>
        <div class='col-4'>
          <div class='circle100 text-center articulo'><%= @articulos.count %></div>
          <h5 class='text-center'>Artículos</h5>
        </div>
      </div>
    </div>
    <!-- Porcentajes
    <div class='col-6 back-dashboard'>
      <h3 class='dash-title'><i class="fa fa-bookmark-o"></i> Porcentaje de Datos</h3>
    </div> -->
  </div>
  <div class='row'>
    <!-- Tickets
    <div class='col-12 back-dashboard'>
      <h3 class='dash-title'><i class="fa fa-bookmark-o"></i> Tickets</h3>
    </div> -->
  </div>
</div>