config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'admin', to: 'admin#index', as: :admin
  get 'examples', to: 'home#index', as: :examples

  resources :categorias, only: [:index, :show] do
    resources :subcategorias, only: [:index, :show]
  end

  resources :subcategorias, only: [:index, :show] do
    resources :articulos, only: [:index, :show]
  end

  namespace :admin do
    resources :categorias do
      collection do
        match 'search' => 'categorias#search', via: [:get, :post], as: :search
      end
    end
    resources :subcategorias do
      collection do
        match 'search' => 'subcategorias#search', via: [:get, :post], as: :search
      end
    end
    resources :articulos do
      collection do
        match 'search' => 'articulos#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
      end
    end
  end

  root 'categorias#index'
end

app/models/subcategoria.rb
# == Schema Information
#
# Table name: subcategorias
#
#  id           :integer          not null, primary key
#  titulo       :string(255)
#  slug         :string(255)
#  posicion     :integer
#  descripcion  :text
#  categoria_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Subcategoria < ActiveRecord::Base
  extend FriendlyId
  friendly_id :titulo, use: :slugged
  validates :titulo, presence: true
  default_scope ->{ order(:posicion) }
  scope :primeros, ->{ limit(5) }
  belongs_to :categoria
  has_many :articulos, inverse_of: :subcategoria, dependent: :delete_all
  accepts_nested_attributes_for :articulos, allow_destroy: true, reject_if: :all_blank
  def to_s
    titulo
  end
end

app/controllers/admin/subcategorias_controller.rb
class Admin::SubcategoriasController < Admin::BaseController
  before_action :set_subcategoria, only: [:show, :edit, :update, :destroy]

  def index
    @q = Subcategoria.includes(:categoria).search(params[:q])
    @subcategorias = @q.result(distinct: true).paginate(page: params[:page])
  end

  def show
    respond_with(@subcategoria)
  end

  def new
    @subcategoria = Subcategoria.new
    respond_with(@subcategoria)
  end

  def edit
  end

  def create
    @subcategoria = Subcategoria.new(subcategoria_params)
    if @subcategoria.save
      respond_with([:admin, @subcategoria])
    else
      render :new
    end
  end

  def update
    if @subcategoria.update(subcategoria_params)
      respond_with([:admin, @subcategoria])
    else
      render :edit
    end
  end

  def destroy
    @subcategoria.destroy
    respond_with([:admin, @subcategoria])
  end

  def search
    index
    render :index
  end

  private
  def set_subcategoria
    @subcategoria = Subcategoria.friendly.find(params[:id])
  end

  def subcategoria_params
    params.require(:subcategoria).permit(:titulo, :posicion, :descripcion, :categoria_id)
  end
end

app/controllers/subcategorias_controller.rb
class SubcategoriasController < ApplicationController
  respond_to :html, :json
  def index
    @subcategorias = Subcategoria.all
    respond_with(@subcategorias)
  end

  def show
    @subcategoria = Subcategoria.friendly.find(params[:id])
    respond_with(@subcategoria)
  end
end

app/views/admin/subcategorias/_form.html.erb
<div class='row'>
  <%= form_for [:admin, @subcategoria] do |f| %>
    <% if @subcategoria.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@subcategoria.errors.count, "error") %> no permitieron guardar los cambios:</h2>

        <ul>
        <% @subcategoria.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class='col-12'>
      <div class='grouped-inputs '>
      <%= f.label :titulo %>
      <%= f.text_field :titulo, placeholder: 'Título de la Subategoría'  %>
      </div>
    </div>
    <div class='col-5'>
      <div class='grouped-inputs '>
        <%= f.label 'Posición' %>
        <%= f.number_field :posicion, placeholder: 'Posición en número'  %>
      </div>
    </div>
    <div class='col-5'>
      <div class='grouped-inputs-select '>
        <%= f.label 'Categoría' %>
        <%= f.collection_select :categoria_id, Categoria.all, :id, :titulo %>
      </div>
    </div>
    <div class='col-12'>
      <div class='grouped-inputs-textarea'>
        <%= f.text_area :descripcion, placeholder: 'Descripción de la Subategoría', class: 'wysiwyg' %>
      </div>
    </div>

    <div class='col-12'>
      <br>
      <div class='float actions'>
        <%= f.submit 'Guardar', class:'btn-default push-right'  %>
        <%= link_to 'Cancelar', admin_subcategorias_path, class:'btn-cancel push-right' %>
      </div>
    </div>

  <% end %>
</div>

app/views/admin/subcategorias/edit.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Subategorías', admin_subcategorias_path %>
    <%= link_to 'Editar Subcategoría', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-th-large fa-lg"></i>
      </span>
      <h3>Editar Subcategoría</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/subcategorias/index.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Subcategorías', admin_categorias_path %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-9'>
      <span class='icon'>
        <i class="fa fa-th-large fa-lg"></i>
      </span>
      <h3>Todas las Subcategorías</h3>
    </div>
    <div class='col-3 float'>
      <%= link_to '<i class="fa fa-plus"></i> Agregar Subcategoría'.html_safe, new_admin_subcategoria_path , class: 'btn-default push-right mt'%>
    </div>
  </div>
  <div class='row'>
    <div class='col-12'>
      <div class='float'>
        <%= search_form_for @q, url: search_admin_subcategorias_path, html: {method: :post} do |f| %>
        <div class='search push-right'>
          <%= f.search_field :titulo_cont, placeholder: 'Buscar por titulo' %>
          <%= f.button 'buscar' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <%= content_tag :th, sort_link(@q, :titulo) %>
            <%= content_tag :th, sort_link(@q, :posicion, 'Posición') %>
            <%= content_tag :th, sort_link(@q, :categoria, 'Categoría') %>
            <th> Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @subcategorias.each do |subcategoria| %>
            <tr>
              <td><%= subcategoria.titulo %></td>
              <td>
                <% if subcategoria.posicion? %>
                  <%= subcategoria.posicion %>
                <%else%>
                  <i class="fa fa-ban"></i>
                <%end%>
              </td>
              <td>
                <span class='label-green'><%= subcategoria.categoria %></span>
              </td>
              <td class='acciones'>
                <%= link_to '<i class="fa fa-plus-square fa-lg"></i>'.html_safe, [:admin, subcategoria], class: 'show' %>
                <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_admin_subcategoria_path(subcategoria), class: 'show' %>
                <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, [:admin, subcategoria], method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= will_paginate @subcategorias %>
    </div>
  </div>
</div>

app/views/admin/subcategorias/new.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Subcategorías', admin_subcategorias_path %>
    <%= link_to 'Nueva Subcategoría', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-th-large  fa-lg"></i>
      </span>
      <h3>Nueva Subcategoría</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/subcategorias/show.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Subcategorías', admin_subcategorias_path %>
    <%= link_to @subcategoria.titulo , '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-th-large  fa-lg"></i>
      </span>
      <h3><%= @subcategoria.titulo %></h3>
    </div>
    <div class='col-12 info'>
      <div class='row'>
        <div class='col-12'>
          <ul>
            <li>
              Su categoría es <b class='green-text'><%= link_to @subcategoria.categoria, admin_categoria_path(@subcategoria.categoria) %></b>.
            </li>
            <li>
              La posicion de esta categoría es <b class='green-text'><%= @subcategoria.posicion %></b>.
            </li>
          </ul>
          <hr>
          <h4>Descripción</h4>
          <p>
            <%= raw @subcategoria.descripcion %>
          </p>
        </div>
        <div class='col-12'>
          <div class='float'>
            <%= link_to 'Editar', edit_admin_subcategoria_path(@subcategoria), class:'btn-default push-right' %>
            <%= link_to 'Regresar', admin_subcategorias_path, class:'btn-gray push-right' %>
        </div>
      </div>
    </div>
  </div>
</div>