config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'admin', to: 'admin#index', as: :admin
  get 'examples', to: 'home#index', as: :examples

  resources :categorias, only: [:index, :show] do
    resources :subcategorias, only: [:index, :show]
  end

  resources :subcategorias, only: [:index, :show] do
    resources :articulos, only: [:index, :show]
  end

  namespace :admin do
    resources :categorias do
      collection do
        match 'search' => 'categorias#search', via: [:get, :post], as: :search
      end
    end
    resources :subcategorias do
      collection do
        match 'search' => 'subcategorias#search', via: [:get, :post], as: :search
      end
    end
    resources :articulos do
      collection do
        match 'search' => 'articulos#search', via: [:get, :post], as: :search
      end
    end
    resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
      end
    end
  end

  root 'categorias#index'
end

app/models/categoria.rb
# == Schema Information
#
# Table name: categorias
#
#  id         :integer          not null, primary key
#  titulo     :string(255)
#  slug       :string(255)
#  prioridad  :integer
#  visible    :boolean
#  created_at :datetime
#  updated_at :datetime
#  icon       :string(255)
#  color      :string(255)
#

class Categoria < ActiveRecord::Base
  extend FriendlyId
  friendly_id :titulo, use: :slugged
  has_many :subcategorias, inverse_of: :categoria, dependent: :delete_all
  accepts_nested_attributes_for :subcategorias, allow_destroy: true, reject_if: :all_blank

  validates :titulo, presence: true, uniqueness: true
  default_scope ->{ order(:prioridad) }

  scope :disponibles, ->{where(visible: true)}

  def to_s
    titulo
  end
end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::BaseController
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  def index
    @q = Categoria.search(params[:q])
    @categorias = @q.result(distinct: true).paginate(page: params[:page])
  end

  def show
    respond_with(@categoria)
  end

  def new
    @categoria = Categoria.new
    respond_with(@categoria)
  end

  def edit
  end

  def create
    @categoria = Categoria.new(categoria_params)
    if @categoria.save
      respond_with([:admin, @categoria])
    else
      render :new
    end
  end

  def update
    if @categoria.update(categoria_params)
      respond_with([:admin, @categoria])
    else
      render :edit
    end
  end

  def destroy
    @categoria.destroy
    respond_with([:admin, @categoria])
  end

  def search
    index
    render :index
  end

  private
  def set_categoria
    @categoria = Categoria.friendly.find(params[:id])
  end

  def categoria_params
    params.require(:categoria).permit(:titulo, :slug, :prioridad, :visible, :color, :icon, subcategorias_attributes: [:id, :titulo, :posicion, :descripcion, :_destroy])
  end
end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @categorias = Categoria.disponibles
    respond_with(@categorias)
  end

  def show
    @categoria = Categoria.friendly.find(params[:id])
    respond_with(@categoria)
  end
end

app/views/admin/categorias/_form.html.erb
<%= nested_form_for [:admin, @categoria] do |f| %>
  <div class='row'>
    <% if @categoria.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@categoria.errors.count, "error") %> no permitieron guardar los cambios:</h2>
        <ul>
        <% @categoria.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class='col-12'>
      <div class='grouped-inputs '>
        <%= f.label 'Título' %>
        <%= f.text_field :titulo, placeholder: 'Título de la Categoría' %>
      </div>
    </div>

    <div class="col-5">
      <div class='grouped-inputs'>
        <%= f.label :prioridad %>
        <%= f.number_field :prioridad, placeholder: 'Prioridad en número' %>
      </div>
    </div>
    <div class="col-5">
      <div class="checkbox">
        <%= f.check_box :visible %>
        <label for="categoria_visible"></label>
        <span>Ver en Sitio</span>
      </div>
      <br>
    </div>

    <!-- Iconos
    <div class="col-5">
      <div class='grouped-inputs relative-div'>
        <%= f.label :icon %>
        <%= f.text_field :icon, class: 'value-icon', placeholder: 'Selecciona un Icono' %>
        <div class='icon-select'>
          <i class="fa fa-search-plus"></i>
          <%= render 'iconos' %>
        </div>
      </div>
    </div> -->

    <!-- Color, el default es verde, ver si esto lo limitamos a 5 colores predefinidos
    <div class="col-5">
      <div class='grouped-inputs'>
        <%= f.label :color %>
        <%= f.text_field :color, placeholder: 'Selecciona un Color', class: 'minicolor' %>
      </div>
    </div> -->

    <div class='col-12'>
      <div class='row'>
        <div class='col-3 sidebar'>
          <div class='title'>
            <span class='icon'>
              <i class="fa fa-th-large"></i>
            </span>
            <h4>Editar Subcategorías</h4>
          </div>
          <ul class='content lista-sub'>
            <li class='primer-li'><%= f.link_to_add '<i class="fa fa-plus"></i> Agregar Subcategoría <span id="totalSub" class="indicador-rojo"></span>'.html_safe, :subcategorias , class: 'add-sub', data: {target: '#target'}, onclick: 'listener()' %>
            </li>

            <% if @categoria.subcategorias.count > 0 %>
                <%= f.fields_for :subcategorias do |sub| %>
                  <% if sub.object.slug? %>
                    <li><a class='<%= sub.object.slug%> existe'><i class="fa fa-th-large"></i> <%= sub.object.titulo.truncate(30) %></a></li>
                  <% end %>
                <% end %>
            <% else %>
              <li><%= link_to 'Sin Subcategorías', '' %></li>
            <% end %>
          </ul>
        </div>
        <div class='col-9'>
          <div class='caja-sub' id='target'>
            <%= f.fields_for :subcategorias do |sub| %>
              <% if sub.object.slug? %>
                <div class='add-subcategory oculta <%= sub.object.slug %>'>
              <% else %>
                <div class='add-subcategory nuevo'>
              <% end %>
                  <div class='row title'>
                    <div class='col-9'>
                      <span class='icon'>
                        <i class="fa fa-th-large fa-lg"></i>
                      </span>
                      <h3>Subcategoría</h3>
                    </div>
                    <div class='col-3 float'>
                      <%= sub.link_to_remove '<i class="fa fa-trash"></i> eliminar'.html_safe, class: 'btn-cancel push-right mt', onclick: 'update()'%>
                    </div>
                  </div>
                  <div class='row'>
                    <div class='col-12 info'>
                      <div class='grouped-inputs'>
                        <%= sub.label :titulo %>
                        <%= sub.text_field :titulo, placeholder: 'Agrega titulo de subcategoría' %>
                      </div>
                      <div class='grouped-inputs'>
                        <%= sub.label :posicion %>
                        <%= sub.number_field :posicion, placeholder: 'Posición en número' %>
                      </div>
                      <div class="grouped-inputs-textarea">
                        <%= sub.text_area :descripcion, placeholder: 'Descripción de la subcategoría', class: 'wysiwyg' %>
                      </div>
                    </div>
                  </div>
                </div>
                <% unless sub.object.id %>
                  <script charset="utf-8">
                    $(document).ready(function(){
                      $(".wysiwyg").editable({language: 'es', inlineMode: false, buttons: ["bold", "italic", "underline", "fontSize", "table", "insertVideo", "insertImage", "uploadFile", "insertOrderedList", "insertUnorderedList", "color", "createLink", "redo", "undo"]});
                    });
                  </script>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class='col-12'>
      <br>
      <div class='float actions'>
        <%= f.submit 'Guardar', class:'btn-default push-right'  %>
        <%= link_to 'Cancelar', admin_categorias_path, class:'btn-cancel push-right' %>
      </div>
    </div>
  </div>
<% end %>

<script charset="utf-8">
  function listener() {
    var nuevo = $('.nuevo:visible').length;
    var total = nuevo + 1;
    if (total == 0) {
      $('#totalSub').hide();
    } else {
      $('#totalSub').show();
      $('#totalSub').html(total);
    }
  }
  function update(){
    var actualizar = $('.nuevo:visible').length;
    var total = actualizar - 1;
    if (total == 0) {
      $('#totalSub').hide();
    } else {
      $('#totalSub').show();
      $('#totalSub').html(total);
    }
  }
</script>

app/views/admin/categorias/_iconos.html.erb
<ul class='icon-select-ul'>
  <li><i class="fa fa-adjust"></i></li>
  <li><i class="fa fa-anchor"></i></li>
  <li><i class="fa fa-archive"></i></li>
  <li><i class="fa fa-automobile"></i></li>
  <li><i class="fa fa-arrows"></i></li>
  <li><i class="fa fa-bank"></i></li>
  <li><i class="fa fa-bell"></i></li>
  <li><i class="fa fa-bicycle"></i></li>
  <li><i class="fa fa-bolt"></i></li>
  <li><i class="fa fa-book"></i></li>
  <li><i class="fa fa-briefcase"></i></li>
  <li><i class="fa fa-bug"></i></li>
  <li><i class="fa fa-building"></i></li>
  <li><i class="fa fa-bus"></i></li>
  <li><i class="fa fa-bullhorn"></i></li>
  <li><i class="fa fa-calculator"></i></li>
  <li><i class="fa fa-calendar"></i></li>
  <li><i class="fa fa-camera"></i></li>
  <li><i class="fa fa-car"></i></li>
  <li><i class="fa fa-child"></i></li>
  <li><i class="fa fa-circle"></i></li>
  <li><i class="fa fa-coffee"></i></li>
  <li><i class="fa fa-cog"></i></li>
  <li><i class="fa fa-comment"></i></li>
  <li><i class="fa fa-compass"></i></li>
  <li><i class="fa fa-envelope"></i></li>
  <li><i class="fa fa-female"></i></li>
  <li><i class="fa fa-cutlery"></i></li>
  <li><i class="fa fa-eye"></i></li>
  <li><i class="fa fa-flag"></i></li>
  <li><i class="fa fa-flash"></i></li>
  <li><i class="fa fa-folder"></i></li>
  <li><i class="fa fa-gamepad"></i></li>
  <li><i class="fa fa-gavel"></i></li>
  <li><i class="fa fa-gift"></i></li>
  <li><i class="fa fa-group"></i></li>
  <li><i class="fa fa-heart"></i></li>
  <li><i class="fa fa-inbox"></i></li>
  <li><i class="fa fa-key"></i></li>
  <li><i class="fa fa-laptop"></i></li>
  <li><i class="fa fa-leaf"></i></li>
  <li><i class="fa fa-legal"></i></li>
  <li><i class="fa fa-lock"></i></li>
  <li><i class="fa fa-magic"></i></li>
  <li><i class="fa fa-male"></i></li>
  <li><i class="fa fa-money"></i></li>
  <li><i class="fa fa-plane"></i></li>
  <li><i class="fa fa-plug"></i></li>
  <li><i class="fa fa-road"></i></li>
  <li><i class="fa fa-send"></i></li>
  <li><i class="fa fa-shield"></i></li>
  <li><i class="fa fa-star"></i></li>
  <li><i class="fa fa-tag"></i></li>
  <li><i class="fa fa-ticket"></i></li>
  <li><i class="fa fa-tree"></i></li>
  <li><i class="fa fa-trophy"></i></li>
  <li><i class="fa fa-truck"></i></li>
  <li><i class="fa fa-unlock"></i></li>
  <li><i class="fa fa-user"></i></li>
  <li><i class="fa fa-users"></i></li>
  <li><i class="fa fa-wifi"></i></li>
  <li><i class="fa fa-wrench"></i></li>
  <li><i class="fa fa-wheelchair"></i></li>
</ul>

app/views/admin/categorias/edit.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Categorías', admin_categorias_path %>
    <%= link_to 'Editar Categoría', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-bookmark fa-lg"></i>
      </span>
      <h3>Editar Categoría</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/categorias/index.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
  <%= link_to 'Dashboard', admin_path %>
  <%= link_to 'Categorías', admin_categorias_path %>
</div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-9'>
      <span class='icon'>
        <i class="fa fa-bookmark fa-lg"></i>
      </span>
      <h3>Todas las Categorías</h3>
    </div>
    <div class='col-3 float'>
      <%= link_to '<i class="fa fa-plus"></i> Agregar Categoria'.html_safe, new_admin_categoria_path , class: 'btn-default push-right mt'%>
    </div>
  </div>
  <div class='row'>
    <div class='col-12'>
      <div class='float'>
        <%= search_form_for @q, url: search_admin_categorias_path, html: {method: :post} do |f| %>
        <div class='search push-right'>
          <%= f.search_field :titulo_cont, placeholder: 'Buscar por titulo' %>
          <%= f.button 'buscar' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class='col-12'>
      <table class='table'>
        <thead>
          <tr>
            <%= content_tag :th, sort_link(@q, :titulo) %>
            <%= content_tag :th, sort_link(@q, :prioridad) %>
            <%= content_tag :th, sort_link(@q, :visibilidad) %>
            <!-- Color
            <th>Color</th> -->
            <!-- Iconos
            <th>Icono</th> -->
            <%= content_tag :th, sort_link(@q, :subcategoria, 'Subcategorías') %>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @categorias.each do |categoria| %>
            <tr>
              <td><%= categoria.titulo %></td>
              <td>
                <% if categoria.prioridad? %>
                  <%= categoria.prioridad %>
                <%else%>
                  <i class="fa fa-ban"></i>
                <%end%>
              </td>
              <td>
                <% if categoria.visible %>
                  <div class='green-label'>
                    <i class="fa fa-eye fa-lg"></i>
                  </div>
                <% else %>
                  <div class='red-label'>
                    <i class="fa fa-eye-slash fa-lg"></i>
                  </div>
                <% end %>
              </td>
              <!-- Color
              <td>
                <span class='color-picker' style='background:<%= categoria.color %>;'></span>
              </td> -->
              <!-- Iconos
              <td>
                <i class="fa fa-<%= categoria.icon %>"></i>
              </td> -->
              <td>
                <span class='label-green'><%= categoria.subcategorias.count %></span>
              </td>
              <td class='acciones'>
                <%= link_to '<i class="fa fa-plus-square fa-lg"></i>'.html_safe, [:admin, categoria], class: 'show' %>
                <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_admin_categoria_path(categoria) , class: 'show' %>
                <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, [:admin, categoria], method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
        <%= will_paginate @categorias %>
    </div>
  </div>
</div>

app/views/admin/categorias/new.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Categorías', admin_categorias_path %>
    <%= link_to 'Nueva Categoría', '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-bookmark fa-lg"></i>
      </span>
      <h3>Nueva Categoría</h3>
    </div>
    <div class='col-12 info'>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/categorias/show.html.erb
<% content_for :breadcrumbs do %>
  <div class="breadcrumb">
    <%= link_to 'Dashboard', admin_path %>
    <%= link_to 'Categorías', admin_categorias_path %>
    <%= link_to @categoria.titulo , '' %>
  </div>
<% end %>

<div class='container'>
  <div class='row title'>
    <div class='col-12'>
      <span class='icon'>
        <i class="fa fa-bookmark fa-lg"></i>
      </span>
      <h3><%= @categoria.titulo %></h3>
    </div>
    <div class='col-12 info'>
      <div class='row'>
        <div class='col-12'>
          <ul>
            <li>
              <% if @categoria.prioridad? %>
              La prioridad de esta categoría es <b class='green-text'><%= @categoria.prioridad %></b>
              <%else%>
              Esta categoría aun <b class='red-text'>no</b> tiene prioridad
              <%end%>
              <% if @categoria.visible?  %>
                 y <b class='green-text'>esta visible <i class="fa fa-eye fa-lg"></i></b> en el sitio.
              <%else%>
                y <b class='red-text'>no esta visible <i class="fa fa-eye-slash fa-lg red-text"></i></b> en el sitio.
              <%end%>
            </li>
          </ul>
          <hr>
          <% if @categoria.subcategorias.count > 0 %>
          <div class='row title'>
            <div class='col-9'>
              <span class='icon'>
                <i class="fa fa-th-large fa-lg"></i>
              </span>
              <h3>Subcategorías</h3>
            </div>
            <div class='col-3 float'>
              <%= link_to '<i class="fa fa-plus"></i> Agregar otra Subcategoría'.html_safe, new_admin_subcategoria_path , class: 'btn-default push-right mt'%>
            </div>
          </div>
          <div class='row'>
            <table class='table'>
              <thead>
                <tr>
                  <th>Titulo</th>
                  <th>Posicion</th>
                  <th>Categoria</th>
                  <th> Acciones</th>
                </tr>
              </thead>

              <tbody>
                <% @categoria.subcategorias.each do |subcategoria| %>
                <tr>
                  <td><%= subcategoria.titulo %></td>
                  <td>
                    <% if subcategoria.posicion? %>
                      <%= subcategoria.posicion %>
                    <%else%>
                      <i class="fa fa-ban"></i>
                    <%end%>
                  </td>
                  <td>
                    <span class='label-green'><%= subcategoria.categoria %></span>
                  </td>
                  <td class='acciones'>
                    <%= link_to '<i class="fa fa-plus-square fa-lg"></i>'.html_safe, [:admin, subcategoria], class: 'show' %>
                    <%= link_to '<i class="fa fa-pencil fa-lg"></i>'.html_safe, edit_admin_subcategoria_path(subcategoria), class: 'show' %>
                    <%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, [:admin, subcategoria], method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%else%>
          <div class='row title'>
            <div class='col-9'>
              <span class='icon'>
                <i class="fa fa-th-large fa-lg"></i>
              </span>
              <h3>Sin Subcategorías</h3>
            </div>
            <div class='col-3 float'>
              <%= link_to '<i class="fa fa-plus"></i> Agregar Subcategoría'.html_safe, new_admin_subcategoria_path , class: 'btn-default push-right mt'%>
            </div>
          </div>
          <%end%>
        </div>
        <div class='col-12'>
          <br>
          <div class='float'>
            <%= link_to 'Editar', edit_admin_categoria_path(@categoria), class:'btn-default push-right'  %>
            <%= link_to 'Regresar', admin_categorias_path, class:'btn-cancel push-right'  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>